Feature/file endpoint
brenosss/peticoes-web pull request #12
Opened 2021-01-25 18:16 UTC by JoaoRicardoSimplicio

Endpoint para receber arquivos encodificados do peticoes-client e gerar um novo arquivo docx.

2021-01-27 00:05 UTC, brenosss requested changes

2021-01-27 00:05 UTC, brenosss commented on main/services/file.py
> +                docx_file = open(f'{self.file_manager.file_name}.docx', 'wb')
Fiquei confuso nessa parte, acho que você está fazendo aquela estrategia que te falei de usar arquivo sem extensão, tenta colocar os nomes mais descritivos ex `arquivo_temporario`
Tenta separar em duas funções :
1. É a ultima parte do arquivo salva docx
2. Não é a ultima parte salva sem extensão

2021-01-27 13:09 UTC, JoaoRicardoSimplicio commented on main/services/file.py
> +        try:
tá. Qual seria a melhor forma?
Exception:
    Exception(message)

2021-01-27 13:12 UTC, brenosss commented on main/services/file.py
> +        try:
É que se a exception não vai ser tratada não faz sentido usar o try
Ou você coloca algum tratamento ou tira o try

2021-01-27 13:16 UTC, JoaoRicardoSimplicio commented on main/services/file.py
> +                docx_file = open(f'{self.file_manager.file_name}.docx', 'wb')
1. Nesse caso, está na última parte. 
2. Em qual outra parte eu deveria salvar sem extensão usando esse gerenciador de contexto? Ou a ideia é não usar?

2021-01-27 13:31 UTC, brenosss commented on main/services/file.py
> +                docx_file = open(f'{self.file_manager.file_name}.docx', 'wb')
Eu tô bem confuso de como essa parte tá funcionando, melhor você me explicar em uma chamada

2021-01-31 15:01 UTC, brenosss commented on main/services/file.py
> +            if self.file_manager.slice_current == self.file_manager.slice_count:
```
def _is_last_piece(slice_current, slice_count):
   self.file_manager.slice_current == self.file_manager.slice_count
   
   ```

2021-01-31 15:01 UTC, brenosss commented on main/services/file.py
> +            self.file = open(f'{self.file_manager.file_name}_temporary', 'ab')
self.temporary_file

2021-01-31 15:02 UTC, brenosss commented on main/services/file.py
> +            docx_file = open(f'{self.file_manager.file_name}.docx', 'wb')
stable_file

2021-02-09 21:19 UTC, JoaoRicardoSimplicio commented on main/services/file.py
> +            docx_file = open(f'{self.file_manager.file_name}.docx', 'wb')
corrigido!

2021-02-09 21:19 UTC, JoaoRicardoSimplicio commented on main/services/file.py
> +            self.file = open(f'{self.file_manager.file_name}_temporary', 'ab')
corrigido!

2021-02-09 21:20 UTC, JoaoRicardoSimplicio commented on main/services/file.py
> +            if self.file_manager.slice_current == self.file_manager.slice_count:
corrigido!

2021-02-10 11:28 UTC, gasparpn commented on account/models.py
> +
Essa quebra de linha é desnecessária.

2021-02-10 11:28 UTC, gasparpn commented on account/models.py
> +	REQUIRED_FIELDS = ['username']
Faltou uma quebra de linha no final do arquivo.

2021-02-10 11:28 UTC, gasparpn commented on account/serializers.py
> +        fields = ('username',)
Seria bom ter o email do usuário aqui, se possível.

2021-02-10 11:28 UTC, gasparpn commented on account/serializers.py
> +        fields = ('token', 'username', 'password')
Está sem quebra de linha no final do arquivo. Veja se seu editor consegue adicionar isso automaticamente.

2021-02-10 11:28 UTC, gasparpn commented on account/views.py
> +	#print(serializer)
Essa linha pode ser apagada.

2021-02-10 11:28 UTC, gasparpn commented on account/views.py
> +	print(request.user.id)
Linha desnecessária

2021-02-10 11:28 UTC, gasparpn commented on main/services/file.py
> +            self.temporary_file.close()
Você já fecha esse cara dentro do método `_remove_file_temporary_file`

2021-02-10 11:28 UTC, gasparpn commented on requirements.txt
> +SpeechRecognition==3.8.1
Todas essas libs são necessárias mesmo? Onde essa aqui foi usada?

2021-02-11 14:45 UTC, brenosss approved these changes

2021-02-11 15:22 UTC, merged